#!/usr/bin/env python2
'''
GTK helper to know persistence status
'''
from subprocess import call, check_output, CalledProcessError
import logging
logging.basicConfig(level=logging.INFO)

import gtk

try:
    import vte
except:
    error = gtk.MessageDialog(None, flags=gtk.DIALOG_MODAL,
                              type=gtk.MESSAGE_ERROR,
                              buttons=gtk.BUTTONS_OK,
                              message_format=
                              'You need to install python bindings for libvte'
                              )
    error.run()
    import sys
    sys.exit(1)




### Check-persistence {{{
def get_root_device():
    try:
        return check_output(["check-persistence", "get-root-device"]).strip()
    except CalledProcessError:
        return None


def get_persistence_status():
    '''return one of MOUNTED, LIVE, ABSENT'''
    def sub_check(subcmd):
        ret = call(['check-persistence', subcmd])
        if ret == 0:
            return True
        if ret == 10:
            return False
        raise Exception('Error checking persistence status')
    if sub_check('is-mounted'):
        return 'MOUNTED'
    if sub_check('has-avail-persistence'):
        return 'LIVE'
    return 'ABSENT'
### Check-persistence }}}

### Check virtualization {{{
def check_virtualization():
    '''
    check if freepto is running on a virtualized system.
    return values:
        VIRTUAL
        NOTVIRTUAL
    '''
    def sub_check(subcmd):
        ret = call(['check-virt', subcmd])
        if ret == 0:
            return True
        if ret == 10:
            return False
        raise Exception('Error checking virtualization status')
    if sub_check('is_virtual'):
        return 'VIRTUAL'
    return 'NOTVIRTUAL'

# Check virtaulization }}}

title = "Persistence helper"

class AbsentWindow(gtk.Window):

    def __init__(self, icon):
        gtk.Window.__init__(self, gtk.WINDOW_TOPLEVEL)
        self.set_title(title)
        self.set_border_width(10)
        self.icon = icon
        
        if get_root_device() is not None:
            self.box = gtk.VBox(False, 0)
            text = "Persistence not available. You can create it using this window."
            if check_virtualization() == "VIRTUAL":
                text += "\nWaring: Freepto is running under a virtual machine."

            label = gtk.Label(text)
            self.button = gtk.Button("Create persistence")
            self.button.connect('clicked', self.run_persistence)

            table = gtk.Table(3, 2, True)
            self.passphrase_label = gtk.Label("Passphrase")
            self.passphrase = gtk.Entry()
            self.passphrase.set_visibility(False)

            table.attach(self.passphrase_label, 0, 1, 0, 1)
            table.attach(self.passphrase, 1, 2, 0, 1)

            self.passphrase2_label = gtk.Label("Repeat passphrase")
            self.passphrase2 = gtk.Entry()
            self.passphrase2.set_visibility(False)

            table.attach(self.passphrase2_label, 0, 1, 1, 2)
            table.attach(self.passphrase2, 1, 2, 1, 2)

            random_fill_label = gtk.Label("Use random fill")
            self.random_fill = gtk.CheckButton()

            table.attach(random_fill_label, 0, 1, 2, 3)
            table.attach(self.random_fill, 1, 2, 2, 3)

            emulation = "xterm"
            self.term = vte.Terminal()
            self.term.set_emulation(emulation)

            scrollbar = gtk.VScrollbar()
            scrollbar.set_adjustment(self.term.get_adjustment())

            self.box.add(label)
            self.box.add(table)
            self.box.add(self.button)

            self.box.add(self.term)
            self.box.add(scrollbar)

            self.add(self.box)
        else:
            label = gtk.Label("Disk not found")
            self.add(label)

    def run_persistence(self, widget, data=None):
        passwd = self.passphrase.get_text()
        passwd2 = self.passphrase2.get_text()
        random_fill = self.random_fill.get_active()

        if passwd != "" and passwd==passwd2:
            self.button.set_sensitive(False)
            self.create_persistence(passwd, random_fill)

    def create_persistence(self, passwd, random_fill):
        command = ["makepersistence", "-p", "%s" % passwd, "-r", "%s2" % get_root_device()]
        if os.getuid() != 0:
            command = ["su-to-root", "-X", "-c", " ".join(command)]

        code = self.term.get_child_exit_status()
        self.term.connect("child-exited",
                     lambda term: self.post_persistence(code))
        self.term.fork_command(command[0], command)


        #self.popen = Popen(command)
        #self.check_persistence()

    def check_persistence(self):
        code = self.popen.poll()
        if code is None:
            gobject.timeout_add_seconds(5, self.check_persistence)
        else:
            self.post_persistence(code)

    def post_persistence(self, code):
        '''
        cose da fare dopo che lo script makepersistence ha fatto il suo
        sporco lavoro.
        attualmente ricontrollo lo status della persistenza, aggiorno
        l'icona e chiudo il terminale
        '''
        icon.status = get_persistence_status()
        icon.refresh_icon()
        if code == 0:
            msg = gtk.Label()
            msg.set_markup("Esecuzione completa\n\n" +
                           "sembra essere andato tutto bene\n" +
                           "guarda la finestra per esserne sicuro")
        else:
            msg = gtk.Label()
            msg.set_markup("Errori nell'esecuzione\n\n" +
                           "codice %d" % code)
        self.box.add(msg)


class MountedWindow(gtk.Window):

    def __init__(self):
        gtk.Window.__init__(self, gtk.WINDOW_TOPLEVEL)
        self.set_title(title)
        self.set_border_width(10)

        label = gtk.Label("Persistence mounted.")
        self.add(label)

class LiveWindow(gtk.Window):

    def __init__(self):
        gtk.Window.__init__(self, gtk.WINDOW_TOPLEVEL)
        self.set_title(title)
        self.set_border_width(10)

        label = gtk.Label("Persistence not mounted, but available " +
                                  "(maybe you want to reboot?)")
        self.add(label)


class LiveIcon:
    '''
    A status icon with 3 possible statuses:
        MOUNTED
        LIVE
        ABSENT
    '''

    def __init__(self):
        self.icon = gtk.StatusIcon()
        self.status = None
        self.refresh_icon()
        try:
            self.status = get_persistence_status()
        except Exception:
            logging.exception("Status unknown")
        self.dialog = None
        self.refresh_icon()
        self.icon.connect("activate", self.show_popup)
        self.icon.connect("popup-menu", self.right_click_event)

    def refresh_icon(self):
        if self.status == 'MOUNTED':
            self.icon.set_from_stock(gtk.STOCK_YES)
            self.icon.set_tooltip("Persistence mounted")
        elif self.status == 'LIVE':
            self.icon.set_from_stock(gtk.STOCK_NO)
            self.icon.set_tooltip("Persistence not mounted, but available " +
                                  "(maybe you want to reboot?)")
        elif self.status == 'ABSENT':
            self.icon.set_from_stock(gtk.STOCK_CDROM)
            self.icon.set_tooltip("Persistence not available " +
                                  "(do you want to create it?)")
        else:
            self.icon.set_from_stock(gtk.STOCK_NEW)
            self.icon.set_tooltip('Checking...')

    def right_click_event(self, icon, button, time):
        menu = gtk.Menu()
        quit = gtk.MenuItem("Quit")
        quit.connect("activate", gtk.main_quit)
        menu.append(quit)
        menu.show_all()
        menu.popup(None, None, gtk.status_icon_position_menu,
                   button, time, self.icon)

    def show_popup(self, widget):
        '''
        this is the main informational popup; will show basic informational
        and act as "wizard"
        '''
        if self.status == 'ABSENT':
            window = AbsentWindow(self)
        elif self.status == 'LIVE':
            window = LiveWindow()
        else:
            window = MountedWindow()
        window.show_all()


if __name__ == '__main__':
    import os
    os.environ['PATH'] += ':.'
    icon = LiveIcon()
    gtk.main()

# vim: set ft=python ts=4 sw=4 et fdm=marker:
